.git
**/bin
**/obj
**/__pycache__
**/node_modules
**/data
**/secrets
**/.env
**/*.db
**/*.db-wal
**/*.db-shm
**/*.dpapi
**/admin_password.txt
**/*.zip
outputs
third_party


# Offline Go module source is part of the reproducible GeoIP helper build.
!tools/NextTraceGeoHelper/dependency-source/**/*.zip
